refs = {
    logo: document.querySelector('.site-logo'),
    header: document.querySelector('.header'),
    navLinkHome: document.querySelector('.home-js'),
    navLinkLibrary: document.querySelector('.library-js'),
    headerButtons: document.querySelector('.header-buttons'),
    burger: document.querySelector('.hamburger'),
    overlayHeader: document.querySelector('.overlay'),
    nav: document.querySelector('.page-nav'),
    searchForm: document.querySelector('.search-form'),
    siteNav: document.querySelector('.site-navigation'),
    buttonWatched: document.querySelector('.button-watched-js'),
    buttonQueue: document.querySelector('.button-queue-js'),
    buttonHomeOnBurger: document.querySelector('.site-navigation-on-burger__link-home-js'),
    buttonLibraryOnBurger: document.querySelector('.site-navigation-on-burger__link-library-js'),
    galleryList: document.querySelector('.list-films'),
    filmsSection: document.querySelector('.films-js'),
    filmViewSection: document.querySelector('.film-view-js'),
    pagination: document.querySelector('.pagination'),
    warningMessage: document.querySelector('.header-warning'),
    spiner: document.querySelector('.loader-overlay'),
    teamSection: document.querySelector('.team'),
    teamList: document.getElementById('team-list'),
    footerLink: document.getElementById('footer__link'),    
    profileModal: document.getElementById('profile'),
    profileCloseBtn: document.querySelector('.profile__close'),
    profileContent: document.querySelector('.profile-content')
}